## Clientes Banco

Genero nuevos atributos para el dataset

In [1]:
# Importo librerias
import pandas as pd
import numpy as np

In [2]:
# Instalo duckdb
%pip install jupysql
%pip install duckdb-engine

Collecting jupysql
  Downloading jupysql-0.11.1-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: prettytable>=3.12.0 in /usr/local/lib/python3.13/dist-packages (from jupysql) (3.18.0)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (from jupysql) (2.1.1)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.13/dist-packages (from jupysql) (0.6.0)
Requirement already satisfied: ipython-genutils>=0.1.0 in /usr/local/lib/python3.13/dist-packages (from jupysql) (0.2.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from jupysql) (3.1.6)
Requirement already satisfied: sqlglot>=11.3.7 in /usr/local/lib/python3.13/dist-packages (from jupysql) (25.20.2)
Collecting jupysql-plugin>=0.4.2 (from jupysql)
  Downloading jupysql_plugin-0.4.5-py3-none-any.whl.metadata (7.8 kB)
Collecting ploomber-core>=0.2.7 (from jupysql)
  Downloading ploomber_core-0.2.27-py3-none-any.whl.metadata (532 bytes)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from ploomber-core>=0.2.7->jupysql) (6.0.3)
Collecting posthog>=3.0 (from ploomber-core>=0.2.7->jupysql)
  Downloading posthog-7.67.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.13/dist-packages (from prettytable>=3.12.0->jupysql) (0.9.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->jupysql) (3.0.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy->jupysql) (4.16.0)
Requirement already satisfied: requests<3.0,>=2.7 in /usr/local/lib/python3.13/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.32.4)
Collecting backoff>=1.10.0 (from posthog>=3.0->ploomber-core>=0.2.7->jupysql)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2026.7.22)
Downloading jupysql-0.11.1-py3-none-any.whl (95 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.1/95.1 kB 3.1 MB/s eta 0:00:00
Downloading jupysql_plugin-0.4.5-py3-none-any.whl (192 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.8/192.8 kB 7.0 MB/s eta 0:00:00
Downloading ploomber_core-0.2.27-py3-none-any.whl (22 kB)
Downloading posthog-7.67.0-py3-none-any.whl (879 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 879.0/879.0 kB 18.7 MB/s eta 0:00:00
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Installing collected packages: backoff, posthog, ploomber-core, jupysql-plugin, jupysql
Successfully installed backoff-2.2.1 jupysql-0.11.1 jupysql-plugin-0.4.5 ploomber-core-0.2.27 posthog-7.67.0
Collecting duckdb-engine
  Downloading duckdb_engine-0.17.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: duckdb>=0.5.0 in /usr/local/lib/python3.13/dist-packages (from duckdb-engine) (1.3.2)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.13/dist-packages (from duckdb-engine) (26.3)
Requirement already satisfied: sqlalchemy>=1.3.22 in /usr/local/lib/python3.13/dist-packages (from duckdb-engine) (2.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.3.22->duckdb-engine) (4.16.0)
Downloading duckdb_engine-0.17.0-py3-none-any.whl (49 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 2.2 MB/s eta 0:00:00
Installing collected packages: duckdb-engine
Successfully installed duckdb-engine-0.17.0

In [3]:
import duckdb

%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

%sql duckdb://

In [4]:
# Carpeta Drive
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [5]:
# Carpetas y archivo a usar
dataset_path = '/content/drive/MyDrive/dmeyf/datasets/'
dataset_file = 'competencia_01_crudo.csv'

In [6]:
# Cargo archivo original
%%sql
create or replace table competencia_01 as
select *
from read_csv_auto("{{dataset_path + dataset_file}}")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Empty DataFrame
Columns: [Success]
Index: []

In [7]:
# Genero nuevos atributos y los guardo en un nuevo archivo

%%sql

COPY
(
  select
  *
  , lag(mpayroll, 1) over (partition by numero_de_cliente order by ori.foto_mes)  as mpayroll_lag
  , lag(mpayroll, 2) over (partition by numero_de_cliente order by ori.foto_mes)  as mpayroll_lag2
  , ( mpayroll - lag(mpayroll, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mpayroll
  , ( mpayroll - lag(mpayroll, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mpayroll_l2
  , round(( mpayroll / paym.mpayroll_prom),2)  as mpayroll_relativa
  , (cseguro_vida + cseguro_auto + cseguro_vivienda + cseguro_accidentes_personales) as cseguros
  , lag(mcuentas_saldo, 1) over (partition by numero_de_cliente order by ori.foto_mes)  as mcuentas_saldo_lag
  , lag(mcuentas_saldo, 2) over (partition by numero_de_cliente order by ori.foto_mes)  as mcuentas_saldo_lag_2
  , ( mcuentas_saldo - lag(mcuentas_saldo, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mcuentas_saldo
  , ( mcuentas_saldo - lag(mcuentas_saldo, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mcuentas_saldo_l2
  , lag(mrentabilidad, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mrentabilidad_lag
  , ( mrentabilidad - lag(mrentabilidad, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mrentabilidad
  , lag(mrentabilidad, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mrentabilidad_lag_2
  , ( mrentabilidad - lag(mrentabilidad, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mrentabilidad_l2
  , lag(mcomisiones, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mcomisiones_lag
  , ( mcomisiones - lag(mcomisiones, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mcomisiones
  , lag(mcomisiones, 2) over (partition by numero_de_cliente order by ori.foto_mes) asmcomisiones_lag_2
  , ( mcomisiones - lag(mcomisiones, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mcomisiones_l2
  , lag(mactivos_margen, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mactivos_margen_lag
  , ( mactivos_margen - lag(mactivos_margen, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mactivos_margen
  , lag(mactivos_margen, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mactivos_margen_lag_2
  , ( mactivos_margen - lag(mactivos_margen, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mactivos_margen_l2
  , lag(mpasivos_margen, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mpasivos_margen_lag
  , ( mpasivos_margen - lag(mpasivos_margen, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mpasivos_margen
  , lag(mpasivos_margen, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mpasivos_margen_lag_2
  , ( mpasivos_margen - lag(mpasivos_margen, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mpasivos_margen_l2
  , lag(mcuenta_corriente, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mcuenta_corriente_lag
  , ( mcuenta_corriente - lag(mcuenta_corriente, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mcuenta_corriente
  , lag(mcuenta_corriente, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mcuenta_corriente_lag_2
  , ( mcuenta_corriente - lag(mcuenta_corriente, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mcuenta_corriente_l2
  , lag(mcaja_ahorro, 1) over (partition by numero_de_cliente order by ori.foto_mes)  as  mcaja_ahorro_lag
  , ( mcaja_ahorro - lag(mcaja_ahorro, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mcaja_ahorro
  , lag(mcaja_ahorro, 2) over (partition by numero_de_cliente order by ori.foto_mes)  as  mcaja_ahorro_lag_2
  , ( mcaja_ahorro - lag(mcaja_ahorro, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mcaja_ahorro_l2
  , lag(mautoservicio, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mautoservicio_lag
  , ( mautoservicio - lag(mautoservicio, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mautoservicio
  , lag(mautoservicio, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mautoservicio_lag_2
  , ( mautoservicio - lag(mautoservicio, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mautoservicio_l2
  , lag(mtarjeta_visa_consumo, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mtarjeta_visa_consumo_lag
  , ( mtarjeta_visa_consumo - lag(mtarjeta_visa_consumo, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mtarjeta_visa_consumo
  , lag(mtarjeta_visa_consumo, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mtarjeta_visa_consumo_lag_2
  , ( mtarjeta_visa_consumo - lag(mtarjeta_visa_consumo, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mtarjeta_visa_consumo_l2
  , lag(mtarjeta_master_consumo, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mtarjeta_master_consumo_lag
  , ( mtarjeta_master_consumo - lag(mtarjeta_master_consumo, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mtarjeta_master_consumo
  , lag(mtarjeta_master_consumo, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mtarjeta_master_consumo_lag_2
  , ( mtarjeta_master_consumo - lag(mtarjeta_master_consumo, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mtarjeta_master_consumo_l2
  , lag(mprestamos_prendarios, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mprestamos_prendarios_lag
  , ( mprestamos_prendarios - lag(mprestamos_prendarios, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mprestamos_prendarios
  , lag(mprestamos_prendarios, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mprestamos_prendarios_lag_2
  , ( mprestamos_prendarios - lag(mprestamos_prendarios, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mprestamos_prendarios_l2
  , lag(mprestamos_personales, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mprestamos_personales_lag
  , ( mprestamos_personales - lag(mprestamos_personales, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mprestamos_personales
  , lag(mprestamos_personales, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mprestamos_personales_lag_2
  , ( mprestamos_personales - lag(mprestamos_personales, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mprestamos_personales_l2
  , lag(mplazo_fijo_pesos, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mplazo_fijo_pesos_lag
  , ( mplazo_fijo_pesos - lag(mplazo_fijo_pesos, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mplazo_fijo_pesos
  , lag(mplazo_fijo_pesos, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mplazo_fijo_pesos_lag_2
  , ( mplazo_fijo_pesos - lag(mplazo_fijo_pesos, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mplazo_fijo_pesos_l2
  , lag(mplazo_fijo_dolares, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mplazo_fijo_dolares_lag
  , ( mplazo_fijo_dolares - lag(mplazo_fijo_dolares, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mplazo_fijo_dolares
  , lag(mplazo_fijo_dolares, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mplazo_fijo_dolares_lag_2
  , ( mplazo_fijo_dolares - lag(mplazo_fijo_dolares, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mplazo_fijo_dolares_l2
  , lag(mcuenta_debitos_automaticos, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mcuenta_debitos_automaticos_lag
  , ( mcuenta_debitos_automaticos - lag(mcuenta_debitos_automaticos, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mcuenta_debitos_automaticos
  , lag(mcuenta_debitos_automaticos, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mcuenta_debitos_automaticos_lag_2
  , ( mcuenta_debitos_automaticos - lag(mcuenta_debitos_automaticos, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mcuenta_debitos_automaticos_l2
  , lag(mextraccion_autoservicio, 1) over (partition by numero_de_cliente order by ori.foto_mes) as mextraccion_autoservicio_lag
  , ( mextraccion_autoservicio - lag(mextraccion_autoservicio, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mextraccion_autoservicio
  , lag(mextraccion_autoservicio, 2) over (partition by numero_de_cliente order by ori.foto_mes) as mextraccion_autoservicio_lag_2
  , ( mextraccion_autoservicio - lag(mextraccion_autoservicio, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_mextraccion_autoservicio_l2
  , lag(matm, 1) over (partition by numero_de_cliente order by ori.foto_mes) as matm_lag
  , ( matm - lag(matm, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_matm
  , lag(matm, 2) over (partition by numero_de_cliente order by ori.foto_mes) as matm_lag_2
  , ( matm - lag(matm, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_matm_l2
  , lag(Visa_mconsumototal, 1) over (partition by numero_de_cliente order by ori.foto_mes) as Visa_mconsumototal_lag
  , ( Visa_mconsumototal - lag(Visa_mconsumototal, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Visa_mconsumototal
  , lag(Visa_mconsumototal, 2) over (partition by numero_de_cliente order by ori.foto_mes) as Visa_mconsumototal_lag_2
  , ( Visa_mconsumototal - lag(Visa_mconsumototal, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Visa_mconsumototal_l2
  , lag(Visa_mlimitecompra, 1) over (partition by numero_de_cliente order by ori.foto_mes) as  Visa_mlimitecompra_lag
  , ( Visa_mlimitecompra - lag(Visa_mlimitecompra, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Visa_mlimitecompra
  , lag(Visa_mlimitecompra, 2) over (partition by numero_de_cliente order by ori.foto_mes) as  Visa_mlimitecompra_lag_2
  , ( Visa_mlimitecompra - lag(Visa_mlimitecompra, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Visa_mlimitecompra_l2
  , lag(Visa_msaldototal, 1) over (partition by numero_de_cliente order by ori.foto_mes) as Visa_msaldototal_lag
  , ( Visa_msaldototal - lag(Visa_msaldototal, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Visa_msaldototal
  , lag(Visa_msaldototal, 2) over (partition by numero_de_cliente order by ori.foto_mes) as Visa_msaldototal_lag
  , ( Visa_msaldototal - lag(Visa_msaldototal, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Visa_msaldototal_l2
  , lag(Visa_mpagospesos, 1) over (partition by numero_de_cliente order by ori.foto_mes) as Visa_mpagospesos_lag
  , ( Visa_mpagospesos - lag(Visa_mpagospesos, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Visa_mpagospesos
  , lag(Visa_mpagospesos, 2) over (partition by numero_de_cliente order by ori.foto_mes) as Visa_mpagospesos_lag_2
  , ( Visa_mpagospesos - lag(Visa_mpagospesos, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Visa_mpagospesos_l2
  , lag(Master_mconsumototal, 1) over (partition by numero_de_cliente order by ori.foto_mes) as Master_mconsumototal_lag
  , ( Master_mconsumototal - lag(Master_mconsumototal, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Master_mconsumototal
  , lag(Master_mconsumototal, 2) over (partition by numero_de_cliente order by ori.foto_mes) as Master_mconsumototal_lag_2
  , ( Master_mconsumototal - lag(Master_mconsumototal, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Master_mconsumototal_l2
  , lag(Master_mlimitecompra, 1) over (partition by numero_de_cliente order by ori.foto_mes) as Master_mlimitecompra_lag
  , ( Master_mlimitecompra - lag(Master_mlimitecompra, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Master_mlimitecompra
  , lag(Master_mlimitecompra, 2) over (partition by numero_de_cliente order by ori.foto_mes) as Master_mlimitecompra_lag_2
  , ( Master_mlimitecompra - lag(Master_mlimitecompra, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Master_mlimitecompra_l2
  , lag(Master_msaldototal, 1) over (partition by numero_de_cliente order by ori.foto_mes) as Master_msaldototal_lag
  , ( Master_msaldototal - lag(Master_msaldototal, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Master_msaldototal
  , lag(Master_msaldototal, 2) over (partition by numero_de_cliente order by ori.foto_mes) as Master_msaldototal_lag_2
  , ( Master_msaldototal - lag(Master_msaldototal, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Master_msaldototal_l2
  , lag(Master_mpagospesos, 1) over (partition by numero_de_cliente order by ori.foto_mes) as Master_mpagospesos_lag
  , ( Master_mpagospesos - lag(Master_mpagospesos, 1) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Master_mpagospesos
  , lag(Master_mpagospesos, 2) over (partition by numero_de_cliente order by ori.foto_mes) as Master_mpagospesos_lag_2
  , ( Master_mpagospesos - lag(Master_mpagospesos, 2) over (partition by numero_de_cliente order by ori.foto_mes)) as delta_Master_mpagospesos_l2
  , lag(Master_status, 1) over (partition by numero_de_cliente order by ori.foto_mes) as Master_status_lag
  , lag(Master_status, 2) over (partition by numero_de_cliente order by ori.foto_mes) as Master_status_lag_2
  , lag(Visa_status, 1) over (partition by numero_de_cliente order by ori.foto_mes) as Visa_status_lag
  , lag(Visa_status, 2) over (partition by numero_de_cliente order by ori.foto_mes) as Visa_status_lag_2
  , case when ori.mpayroll > (paym.mpayroll_max * .95) then 1 else 0 end as flag_superior_payroll
  , round(( mrentabilidad / paym.mrentabilidad_prom),2)  as mrentabilidad_relativa
    from competencia_01 ori
    inner join
    (
        select foto_mes
        , avg(mpayroll) as mpayroll_prom
        , max(mpayroll) as mpayroll_max
        , avg(mrentabilidad) as mrentabilidad_prom
        from competencia_01
        group by foto_mes
    ) paym
    on ori.foto_mes = paym.foto_mes

)
TO '/content/drive/MyDrive/dmeyf/datasets/competencia_01_fe_Final.csv' (FORMAT CSV, HEADER TRUE);

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Empty DataFrame
Columns: [Success]
Index: []